# Generated by Django 4.1 on 2022-09-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BarangKatalog',
        ),
    ]
