# Generated by Django 4.1 on 2022-09-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_rename_barangwishlist_watchlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watchlist',
            new_name='MyWatchList',
        ),
    ]
